# Generated by Django 3.2.3 on 2021-06-09 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210609_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('phone_number', models.CharField(default='', max_length=30)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('fees_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
