# Generated by Django 3.2.3 on 2021-06-09 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('isbn', models.CharField(default='', max_length=50)),
                ('author', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('description', models.CharField(default='', max_length=50)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('phone_number', models.CharField(default='', max_length=30)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('salary', models.CharField(default='0', max_length=30)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('phone_number', models.CharField(default='', max_length=30)),
                ('date_of_birth', models.DateField(null=True)),
                ('address', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=10)),
                ('salary', models.CharField(default='0', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
