# Generated by Django 3.1.6 on 2021-06-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210623_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='timetable_image',
            field=models.FileField(blank=True, upload_to='post_timetable'),
        ),
    ]
